# Generated by Django 4.2.6 on 2023-10-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0002_rename_imageresult_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='is_correct',
        ),
    ]
