# Generated by Django 4.2.6 on 2023-10-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0006_alter_images_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
