# Generated by Django 4.2.6 on 2023-10-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageResult',
            new_name='Image',
        ),
    ]
