# Generated by Django 4.2.6 on 2023-10-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_processing', '0003_remove_image_is_correct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
    ]
